from .configs import (
    ACTION_RECOGNITION_MODEL_PATH,
    ACTION_DEVICE,
    ARENA_MARK_DETECTOR_PATH,
    BALL_DETECTOR_PATH,
    COURT_IMAGE_PATH,
    DETECTION_BATCH_SIZE,
    DETECTION_CONFIDENCE,
    OUTPUT_VIDEO_PATH,
    PLAYER_DETECTOR_PATH,
    STUBS_DEFAULT_PATH,
    TEAM_1_CLASS_NAME,
    TEAM_2_CLASS_NAME,
)
